// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/asset/asset.proto

package rz_assets_srv_asset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Asset struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{1}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Asset) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type QueryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{2}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AssetsId             int64    `protobuf:"varint,3,opt,name=assetsId,proto3" json:"assetsId,omitempty"`
	AffectNum            int32    `protobuf:"varint,4,opt,name=affectNum,proto3" json:"affectNum,omitempty"`
	Assets               []*Asset `protobuf:"bytes,5,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78e4568551c90fa4, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetAssetsId() int64 {
	if m != nil {
		return m.AssetsId
	}
	return 0
}

func (m *Response) GetAffectNum() int32 {
	if m != nil {
		return m.AffectNum
	}
	return 0
}

func (m *Response) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "rz.assets.srv.asset.Error")
	proto.RegisterType((*Asset)(nil), "rz.assets.srv.asset.Asset")
	proto.RegisterType((*QueryRequest)(nil), "rz.assets.srv.asset.QueryRequest")
	proto.RegisterType((*Response)(nil), "rz.assets.srv.asset.Response")
}

func init() { proto.RegisterFile("proto/asset/asset.proto", fileDescriptor_78e4568551c90fa4) }

var fileDescriptor_78e4568551c90fa4 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x7c, 0x69, 0x9a, 0xbe, 0x76, 0x8b, 0x04, 0x5a, 0x24, 0xb0, 0x2a, 0x90, 0x22, 0x9f, 0x7a,
	0x4a, 0x51, 0xfb, 0x05, 0x54, 0x70, 0xe8, 0x81, 0x20, 0x2c, 0xf1, 0x01, 0x21, 0xde, 0x0a, 0xa4,
	0xb6, 0x2e, 0xb6, 0x03, 0x2a, 0x9f, 0x87, 0xf8, 0x30, 0x94, 0x75, 0x0a, 0x97, 0xc2, 0xa5, 0x5c,
	0xa2, 0x9d, 0xc9, 0xcc, 0xd8, 0x3b, 0x32, 0x9c, 0xae, 0xad, 0xf1, 0x66, 0x54, 0x38, 0x47, 0x3e,
	0x7c, 0x33, 0x66, 0xf0, 0xd8, 0xbe, 0x65, 0x8c, 0x5d, 0xe6, 0xec, 0x4b, 0x18, 0xe5, 0x04, 0x92,
	0x6b, 0x6b, 0x8d, 0x45, 0x84, 0x76, 0x69, 0x34, 0x89, 0x28, 0x8d, 0x86, 0x89, 0xe2, 0x19, 0x4f,
	0xa0, 0xa3, 0xc9, 0x17, 0x4f, 0x0b, 0xd1, 0x4a, 0xa3, 0x61, 0x4f, 0x35, 0x48, 0x8e, 0x20, 0xb9,
	0xac, 0xdd, 0xb5, 0x69, 0x55, 0x2c, 0x83, 0xa9, 0xa7, 0x78, 0xae, 0x39, 0x4d, 0xae, 0x6c, 0x2c,
	0x3c, 0x4b, 0x09, 0x07, 0x77, 0x15, 0xd9, 0x8d, 0xa2, 0xe7, 0x8a, 0xdc, 0x4e, 0x9f, 0xfc, 0x88,
	0xa0, 0xab, 0xc8, 0xad, 0xcd, 0xca, 0x11, 0x0a, 0xf8, 0xef, 0xaa, 0xb2, 0x24, 0xe7, 0x58, 0xd3,
	0x55, 0x5b, 0x88, 0x17, 0x90, 0x50, 0x7d, 0x61, 0xce, 0xef, 0x8f, 0x07, 0xd9, 0x8e, 0xad, 0x32,
	0x5e, 0x49, 0x05, 0x21, 0x0e, 0xa0, 0x1b, 0x04, 0x33, 0x2d, 0xe2, 0x34, 0x1a, 0xc6, 0xea, 0x0b,
	0xe3, 0x19, 0xf4, 0x8a, 0xf9, 0x9c, 0x4a, 0x9f, 0x57, 0x4b, 0xd1, 0xe6, 0xd5, 0xbf, 0x09, 0x1c,
	0x43, 0x27, 0x28, 0x45, 0x92, 0xc6, 0x3f, 0x1e, 0xc6, 0x55, 0xa8, 0x46, 0x39, 0x7e, 0x6f, 0x41,
	0x9f, 0x99, 0x1b, 0xf2, 0x8f, 0x46, 0xe3, 0x14, 0xe2, 0x9c, 0x5e, 0xf1, 0x17, 0xeb, 0xe0, 0x7c,
	0xe7, 0xbf, 0x6d, 0x17, 0xf2, 0x1f, 0xde, 0xc2, 0x11, 0xd7, 0x37, 0xdd, 0xb0, 0x21, 0xaf, 0x6b,
	0xde, 0x2b, 0x30, 0x87, 0xc3, 0xfb, 0xb5, 0x2e, 0x3c, 0x35, 0x89, 0x33, 0xbd, 0x77, 0xde, 0x15,
	0x2d, 0xe8, 0xaf, 0xf2, 0x1e, 0x3a, 0xfc, 0x62, 0x27, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84,
	0x7d, 0x59, 0x73, 0xcc, 0x02, 0x00, 0x00,
}
